### PR TITLE
Adds gitignore for dotnet

### PR DESCRIPTION
**Pull request by rossgrambo**

### CODE REVIEW

**Comment by zhenlan** [comment]
Any reason launchSettings.json is not included?

https://github.com/Azure/AppConfiguration/blob/main/.gitignore#L58C1-L64C40

**Comment by zhenlan** [comment]
> Any reason launchSettings.json is not included?
> 
> https://github.com/Azure/AppConfiguration/blob/main/.gitignore#L58C1-L64C40

@rossgrambo @mrm9084 can we copy the gitignore from the AppConfiguration repo?

**Comment by rossgrambo** [comment]
@zhenlan It was intentionally not added. `launchSettings.json` is no longer recommended to be ignored. It used to be but was removed from the recommended gitignore in [github's PR](https://github.com/github/gitignore/pull/2705). Apparently there's reasons why it should be checked in. Secrets should be done with the SecretManager instead.

**Comment by zhenlan** [comment]
> This settings will be useful if shared among project member

We don't have any scenarios that need shared launch settings, but it is repeatedly causing leaked secrets. We force devs to remove it from PRs manually. We can add it when we have a need.

**Pull request merged**
